scoreboard players set @a[scores={KingTalk=<#LastKingOfTyreMeetID#>,KingPActive=0,KingPDestroyed=0}] KingTalk <#LastKingOfTyreRequestID#>
scoreboard players set @a[scores={KingTalk=<#LastKingOfTyreYesResponseID#>}] KingTalk <#LastKingOfTyrePostYesResponseSilenceID#>
scoreboard players set @a[scores={KingTalk=<#LastKingOfTyreNoResponseID#>}] KingTalk <#LastKingOfTyrePostNoResponseSilenceID#>
scoreboard players set @a[scores={KingTalk=<#LastKingOfTyreActivateThreeSeaGateID#>..<#LastKingOfTyreActivateThreeCathedralID#>}] KingTalk <#LastKingOfTyrePostActivateThreeSilenceID#>
scoreboard players set @a[scores={KingTalk=<#LastKingOfTyrePostActivateTwoSilenceID#>,KingP1Victory=0,KingP2Victory=1,KingP3Victory=1,KingP4Victory=1,KingPDestroyed=0}] KingTalk <#LastKingOfTyreActivateThreeSeaGateID#>
scoreboard players set @a[scores={KingTalk=<#LastKingOfTyrePostActivateTwoSilenceID#>,KingP1Victory=1,KingP2Victory=0,KingP3Victory=1,KingP4Victory=1,KingPDestroyed=0}] KingTalk <#LastKingOfTyreActivateThreeWharfsID#>
scoreboard players set @a[scores={KingTalk=<#LastKingOfTyrePostActivateTwoSilenceID#>,KingP1Victory=1,KingP2Victory=1,KingP3Victory=0,KingP4Victory=1,KingPDestroyed=0}] KingTalk <#LastKingOfTyreActivateThreeDepthsID#>
scoreboard players set @a[scores={KingTalk=<#LastKingOfTyrePostActivateTwoSilenceID#>,KingP1Victory=1,KingP2Victory=1,KingP3Victory=1,KingP4Victory=0,KingPDestroyed=0}] KingTalk <#LastKingOfTyreActivateThreeCathedralID#>
scoreboard players set @a[scores={KingTalk=<#LastKingOfTyreActivateFourID#>,KingPDestroyed=0}] KingTalk <#LastKingOfTyreDeathRequestID#>
scoreboard players set @a[scores={KingTalk=<#LastKingOfTyrePostActivateTwoSilenceID#>..<#LastKingOfTyrePostActivateThreeSilenceID#>,KingPActive=4..,KingPDestroyed=0}] KingTalk <#LastKingOfTyreActivateFourID#>
scoreboard players set @a[scores={KingTalk=<#LastKingOfTyreActivateNonResponseID#>..<#LastKingOfTyreActivateNoID#>}] KingTalk <#LastKingOfTyrePostActivateTwoSilenceID#>
scoreboard players set @a[scores={KingTalk=<#LastKingOfTyreMeetID#>..<#LastKingOfTyreRequestID#>,KingPActive=1..,KingPDestroyed=0}] KingTalk <#LastKingOfTyreActivateNonResponseID#>
scoreboard players set @a[scores={KingTalk=<#LastKingOfTyrePostYesResponseSilenceID#>,KingPActive=2..,KingPDestroyed=0}] KingTalk <#LastKingOfTyreActivateYesID#>
scoreboard players set @a[scores={KingTalk=<#LastKingOfTyrePostNoResponseSilenceID#>,KingPActive=2..,KingPDestroyed=0}] KingTalk <#LastKingOfTyreActivateNoID#>
scoreboard players set @a[scores={KingTalk=<#LastKingOfTyreDeadID#>..<#LastKingOfTyreSorrowID#>}] KingTalk <#LastKingOfTyreFinalSilenceID#>
scoreboard players set @a[scores={KingTalk=..<#LastKingOfTyreDeathRequestID#>,KingDead=2}] KingTalk <#LastKingOfTyreDeadID#>
scoreboard players set @a[scores={KingTalk=..<#LastKingOfTyreDeathRequestID#>,KingDead=0,KingPDestroyed=1..}] KingTalk <#LastKingOfTyreSorrowID#>