scoreboard objectives add McSrT25cr7sOSDAR dummy
scoreboard objectives add +fkbyUV+P53ehaQp dummy
scoreboard objectives add H1qid1s1K.n6EXX8 dummy
scoreboard objectives add Zlb0jsE0Nk.TxzSr dummy
scoreboard objectives add _XLxGTCjws-yMXcr trigger
scoreboard objectives add f5nm9bx8r4aR9n2K dummy
scoreboard objectives add 055RiSY9Fk0_GllY dummy
scoreboard objectives add Rwo6_F5b7htWKYHn dummy
scoreboard objectives add 4lFseVf.IRefhvg8 dummy
scoreboard objectives add L+mDwe8JSzGqAc3P dummy
scoreboard objectives add v-i9JprH8G73N9wn dummy
scoreboard objectives add odKJ7JjpwUVt_N9b dummy
scoreboard objectives add 9mEYaMzed-tn4C-O dummy
scoreboard objectives add 9KNkbypJOgvDKgCw dummy
scoreboard objectives add ieMvjGl+s_BSdmyR dummy
scoreboard objectives add WVe5RqThZsOZV58+ dummy
scoreboard objectives add 9zZXXHJTCIsVx0TW dummy
scoreboard objectives add vpUeaG2KE3nlEQP2 dummy
scoreboard objectives add tQyTp1XzVGwrPRH- dummy
scoreboard objectives add gflLIvwG0Zxgtg+f deathCount
scoreboard objectives add M4yRZuLXLTl08P+0 dummy
scoreboard objectives add D_.VVb4Qh65P-KWF dummy
scoreboard objectives add ZpPhk3MN8_U5e+_Z dummy
scoreboard objectives add oZ7XerqKdJbfsiRf dummy
scoreboard objectives add QYsfNkkqHrQgvUJ6 dummy
scoreboard objectives add cjAtNMpAQWEF0ce2 deathCount
scoreboard objectives add b18YzqdzNCAsGGis dummy
scoreboard objectives add Ks3WNzjk5FjBI4q0 dummy
scoreboard objectives add LKzdjQ2vYr2f6dUa dummy
scoreboard objectives add O9iaB30NG9xuNsLV dummy
scoreboard objectives add R-duyN6aJ5NF.83S dummy
scoreboard objectives add SmiETr5m9kRDaEVN dummy
scoreboard objectives add kHLWnj-8TLRSduxI dummy
scoreboard objectives add -PkkC0pkMQn_x4Ct dummy
scoreboard objectives add NDL19IVuh0kzPDJh dummy
scoreboard objectives add z+tyABdRf5AorOYw dummy
scoreboard objectives add wVbg_ayxv6zYITUV dummy
scoreboard objectives add 2O.NYgQrPk718K9F dummy
scoreboard objectives add k5NVqZtMR_KCAkZg deathCount
scoreboard objectives add _AJJR-dEZHUb5q+l dummy
scoreboard objectives add myJG7FuS-KhNjARc dummy
scoreboard objectives add gd_vCppihMeOmnTF dummy
scoreboard objectives add zWN0CRPO5D9iI1HE dummy
scoreboard objectives add ZVTr_WjCuOvpZr_5 dummy
scoreboard objectives add KxlY+gSb9efqT.eR dummy
scoreboard objectives add RTLXGE9VQmRRQ.T+ dummy
scoreboard objectives add L3JCGas9J0wWXLeJ dummy
scoreboard objectives add j+6lX-IsBbFgKpzX dummy
scoreboard objectives add 60d8Dwh6RvkH+i9o dummy
scoreboard objectives add H2lAv47B-yUItTjY dummy
scoreboard objectives add r9d40uXjfuZC6uRO dummy
scoreboard objectives add q52dZ0E4NwDpvvbA dummy
scoreboard objectives add lH3o5cjGcmYUQ96E dummy
scoreboard objectives add ERZSPmPbtT9SCqbF dummy
scoreboard objectives add 4SfShyIn1Nqwj-EW dummy
scoreboard objectives add 8J9O33imbmWbA7OL dummy
scoreboard objectives add lr3ONyC2bZRh1YfP dummy
scoreboard objectives add 223_hGL2KXhaJdZn dummy
scoreboard objectives add WQOcSQ-LGwqm9KNJ dummy
scoreboard objectives add hLcgTCIrSukU3+iI dummy
scoreboard objectives add sZQT66D41kpTGugO dummy
scoreboard objectives add rPjN6dTd6vmwF0By dummy
scoreboard objectives add IatnnYj_k4b9S_pd dummy
scoreboard objectives add JHKKMZ7ortKFUDND dummy
scoreboard objectives add HXgAvMFwOSLO+MHO dummy
scoreboard objectives add dCdcPvj8cI6y903O dummy
scoreboard objectives add -gS0TUaWZKGMNxDN dummy
scoreboard objectives add svlKMe.vxAeVv9ym dummy
scoreboard objectives add mLw1_SHuvl4_3Rx6 dummy
scoreboard objectives add kugmQknE-99VJINj dummy
scoreboard objectives add WWmIpo781Vl_NNkG dummy
scoreboard objectives add cAwWJwCaEjtet1lm dummy
scoreboard objectives add +b8qg+-lfW00Wdsd dummy
scoreboard objectives add bzdFAjnNavldW950 dummy
scoreboard objectives add neM5wYBj4ZJFT8vB dummy
scoreboard objectives add ABdVGWYtK4dlKJTw dummy
scoreboard objectives add kdJ-OTtT6Ksybb-3 dummy
scoreboard objectives add ZxPIhOn5VJ.IT+hk dummy
scoreboard objectives add K0oC-Ir9RA4AWbZX minecraft.custom:minecraft.sleep_in_bed
scoreboard objectives add _ARmEkGd_DsNBQRp dummy
scoreboard objectives add UZGXspwtP8I6JiOT dummy
scoreboard objectives add eHuKtMXlpnkrR6lA dummy
scoreboard objectives add D6BObnS_lZ.-zRX3 dummy
scoreboard objectives add _lEf-NDJvdDLk5J8 dummy
scoreboard objectives add ilR6Q1CT9B4gMfJw dummy
scoreboard objectives add j4vqrry8e66AgPky dummy
scoreboard objectives add zm1kQG8+tcY-5tPg dummy
scoreboard objectives add f7FZrI3FphdtKnYp dummy
scoreboard objectives add 0XD_UojS..U07Blc minecraft.custom:minecraft.damage_blocked_by_shield
scoreboard objectives add wQoYvSsOXSEwa+eu dummy
scoreboard objectives add PaH6acPqrmgD9nu0 dummy
scoreboard objectives add W3OVEPVr+6pv2gKn dummy
scoreboard objectives add 149DS3asnfLN7zMV dummy
scoreboard objectives add .jIiiT-BKhsv07N3 dummy
scoreboard objectives add 5uT.W9fMtGY6-m-l dummy
scoreboard objectives add diQ3.UfiHQYQ0PB9 dummy
scoreboard objectives add vD7HI1y0ky0wN53M dummy
scoreboard objectives add 4yZ2RNFBNeW3-pqh dummy
scoreboard objectives add mpr1GIG7WN0WL0wR dummy
scoreboard objectives add O8_SaEwsXPZBUZv3 dummy
scoreboard objectives add nLeNY7LLjc7GW.cA dummy
scoreboard objectives add bEDPcJnxv7RJYWIz dummy
scoreboard objectives add UBl5ebtr_TJRpsIF dummy
scoreboard objectives add JeaJsRKDZza+yIix dummy
scoreboard objectives add Ux2lcw-NBJkQ8wZR dummy
scoreboard objectives add 78QWe4Xctlx7iCoa dummy
scoreboard objectives add qBiarwqWnjtLqBOd dummy
scoreboard objectives add rk5p6L5IU1KWACjE dummy
scoreboard objectives add mLo7JkdnkZRoZgsQ dummy
scoreboard objectives add WHk21K4MBaGCA9Y- dummy
scoreboard objectives add vF53swKo6JsHh+qg dummy
scoreboard objectives add o.o8JQ0.CCpTz3c6 dummy
scoreboard objectives add 3rNutUILjKbBTQnK dummy
scoreboard objectives add X6yA-_vyO-qtmhJR dummy
scoreboard objectives add ezI9B70j.XrzUwH5 dummy
scoreboard objectives add IIBlC2ycf6UlcIes dummy
scoreboard objectives add vYnWCSIrx5eL0_rT dummy
scoreboard objectives add GzVzbx2EguGxRg.n dummy
scoreboard objectives add -KElhHA5RIQyIC4P dummy
scoreboard objectives add rCwR6JgJFPSOXfvm dummy
scoreboard objectives add HolAt8.byvruHpdt dummy
scoreboard objectives add HCv_O4U9g_ezBpd3 dummy
scoreboard objectives add BU3Qf4ctOFZXxOuX dummy
scoreboard objectives add _ob_fmw5R3CM9TVb dummy
scoreboard objectives add 99U+r2nhFTwAKng1 dummy
scoreboard objectives add CxVzrRZ37KMQXw_B dummy
scoreboard objectives add vqsTna5b4fREF4gU dummy
scoreboard objectives add 3mC9rX6bZjPrxYvW dummy
scoreboard objectives add ZYfw6IDzWDaID.BI dummy
scoreboard objectives add JlwButtu-G_rj32C dummy
scoreboard objectives add 8PLO5meIA75ktsxF dummy
scoreboard objectives add fGCZLG9yqWAxOJp9 dummy
scoreboard objectives add 93mbLgig0G00smkG dummy
scoreboard objectives add iS10M6GhY4b711rg dummy
scoreboard objectives add Iq+XLpGiQeR4KU8o dummy
scoreboard objectives add E4HKRZ+ERAh+kO4u dummy
scoreboard objectives add O-iYDqyxfK5Y5DgD dummy
scoreboard objectives add gQ6nNA9TDD3RdRRh dummy
scoreboard objectives add n3hw-Z76w5-uJlNJ dummy
scoreboard objectives add Si3kY8vu64MZrRHz minecraft.custom:minecraft.damage_dealt
scoreboard objectives add Z6UaLns0tn2fM6hA dummy
scoreboard objectives add -+uIXk7npz4hZSd_ dummy
scoreboard objectives add RuPrlwHRAPU8utCi dummy
scoreboard objectives add KRShZ_IkA7IVI-zH dummy
scoreboard objectives add JCc5j7PqnVX82jbR dummy
scoreboard objectives add 6qltFCGA265rFM56 dummy
scoreboard objectives add YZC4gWN9NQAyeYLg dummy
scoreboard objectives add Gr1XOhVQWFkPgtkx dummy
scoreboard objectives add K3iGPZOZ_H.KbLjr dummy
scoreboard objectives add bM+YhQBdz_5rFUFI dummy
scoreboard objectives add kk3AZLptX7.GuOjs dummy
scoreboard objectives add yJTUXGPiL-DPc5AZ dummy
scoreboard objectives add qORwEnkojJrm.0m+ dummy
scoreboard objectives add Qz2rLYIIbcLPSF21 dummy
scoreboard objectives add 41eNq3iLqwbVCarK dummy
scoreboard objectives add PSLLxCXht-rsVWx. dummy
scoreboard objectives add pE1CjpEWr+n4YFEE dummy
scoreboard objectives add coLrWBu_a_iP-X6W dummy
scoreboard objectives add tsv5bq6Q8EMyV6fY dummy
scoreboard objectives add JqZqeAy+37W3cIoT dummy
scoreboard objectives add Dw4tKd4uxX-BLi6A dummy
scoreboard objectives add 3BeH.LrC6cq.D-aY dummy
scoreboard objectives add ui.2L+4jvLfM-Nlr dummy
scoreboard objectives add tOwGbRxPzibF7s8A dummy
scoreboard objectives add -45_5SDY.njqLPrh dummy
scoreboard objectives add Bz.-jq7_XEp---hl dummy
scoreboard objectives add FZT97U_J7JBjg8yn dummy
scoreboard objectives add YnDEvbOwy8k38KEh dummy
scoreboard objectives add 96ZlId4.hiXwNhtd dummy
scoreboard objectives add GqnW+F-SV_8c-e9w dummy
scoreboard objectives add XRFq0w8onTElNpcV dummy
scoreboard objectives add s-5_dDWg51LTXBle dummy
scoreboard objectives add syq1f_IUK4NG4hgF dummy
scoreboard objectives add WLVwpGO4i-oQbqH2 dummy
scoreboard objectives add SI1RcbsePyf_IIW_ dummy
scoreboard objectives add FqUf0UusIFGLy6Nj dummy
scoreboard objectives add altXpcDt_xXouVyQ dummy
scoreboard objectives add mRx5VY9OvJgIfIcs dummy
scoreboard objectives add KuU8kzK.HaK4zphC dummy
scoreboard objectives add P22meFGVYKcW6mkk minecraft.custom:minecraft.crouch_one_cm
scoreboard objectives add K4se2QD6WEqhBgHR minecraft.custom:minecraft.walk_one_cm
scoreboard objectives add VQtqEPYihPdfJD0R minecraft.custom:minecraft.sprint_one_cm
scoreboard objectives add Da-UUq6f4Lf5PhQ+ dummy
scoreboard objectives add -aiBLtlR6rbRakkJ dummy
scoreboard objectives add SnvWVpkOGH-sTNLs dummy
scoreboard objectives add lftaCc3EnIcMVZoj dummy
scoreboard objectives add N8wby7c9_yLnuyZN dummy
scoreboard objectives add r-PzazChS8jbaRXQ dummy
scoreboard objectives add W3IlGf1Bli-ghKqA dummy
scoreboard objectives add niXEKvwT3njWH_in minecraft.custom:minecraft.damage_taken
scoreboard objectives add Lyye70-3vkj7MsTV minecraft.custom:minecraft.damage_absorbed
scoreboard objectives add XbHbi53zTkG6aZcQ dummy
scoreboard objectives add Yi2j+UB3orf3RVHq minecraft.custom:minecraft.fall_one_cm
scoreboard objectives add uJBGUs5m5U3xs3lV dummy
scoreboard objectives add D5XS8qx1Z3thyF4e dummy
scoreboard objectives add VLUBchW.Hay4Ra4P dummy
scoreboard objectives add V4V1_BbrAZPFz_Z- trigger
scoreboard objectives add tO2LXvg92S.revOR dummy
scoreboard objectives add njD8i+PzwYCWmeEv dummy
scoreboard objectives add XP4-2eZh7WrYoS1d dummy
scoreboard objectives add byKX2_eqgmmYJEre dummy
scoreboard objectives add Jkm9pt8L2M.tuS9H dummy
scoreboard objectives add DmX+6WBr1.6-uN73 dummy
scoreboard objectives add lfbp-wUHs3yZGRD5 dummy
scoreboard objectives add 1J9G45IqILQqiE67 dummy
scoreboard objectives add VYpo03GO+rKi59zb dummy
scoreboard objectives add Qoe3lKRjggpC_I7b dummy
scoreboard objectives add p1ReA2G_xsCtDgXN dummy
scoreboard objectives add ZuGl0RaLBryC5YUo dummy
scoreboard objectives add Yil+Eia5XVG2pWbJ dummy
scoreboard objectives add yYMZQeeb5cdluIIb dummy
scoreboard objectives add x0mpQCjiyV.xuVQ8 dummy
scoreboard objectives add ZCWcjuyv5p8.LcIg dummy
scoreboard objectives add BEYy2N1vTCrZ.aYF dummy
scoreboard objectives add N..yu79CAmBn_sEp dummy
scoreboard objectives add 3UrLDFu8Mdv89c13 dummy
scoreboard objectives add 9CaWR+Y7czJ8SaOJ dummy
scoreboard objectives add Dtan.E+6-tsH+aY2 dummy
scoreboard objectives add 5qAj5XooP6Yt6Rhx dummy
scoreboard objectives add yHvSD.aRhtLTeJj4 dummy
scoreboard objectives add d_jPyagsa81Sdgyv dummy
scoreboard objectives add b-_l8wXsCq4thTzU dummy
scoreboard objectives add xtg480v0EtZpt+jw dummy
scoreboard objectives add iGvq5sOoGQ3eShve dummy
scoreboard objectives add LLdyWag5w-CPvvwI dummy
scoreboard objectives add fqY70jM07N+J-xc1 dummy
scoreboard objectives add UfXX8.vXL.-.2SCv dummy
scoreboard objectives add yXT0qUuhOOC3BVPR dummy
scoreboard objectives add FtQ2XyoidN9DtYft dummy
scoreboard objectives add 02Fo_z.sA6raSdLq dummy
scoreboard objectives add neXn2WOfsMbqVEwb dummy
scoreboard objectives add fO2fHfES6kEFgEMp dummy
scoreboard objectives add pvamq.RcrSa28nd. dummy
scoreboard objectives add aWfm5k4Q0QqBKsAa dummy
scoreboard objectives add kmCdbjVGsDFmDE6v dummy
scoreboard objectives add ir1RHjva1wnaxLT7 dummy
scoreboard objectives add z_eJ1sm8wrrPlO4_ minecraft.custom:minecraft.damage_dealt
scoreboard objectives add coE7kO7JKb2uKIDs dummy
scoreboard objectives add ppm9PV-eKCj1TLUo dummy
scoreboard objectives add 4QIcm9t-cW5DTl21 dummy
scoreboard objectives add 5LRrFdE-l5O.UnVz dummy
scoreboard objectives add -b+723GWY.mRicql dummy
scoreboard objectives add ifJbwDYMRQIlF8Ux dummy
scoreboard objectives add .8C9ofoqODkfoUgx dummy
scoreboard objectives add jw1OislyTCQyu4qE dummy
scoreboard objectives add 60NfbewghO.lqdg0 dummy
scoreboard objectives add 0AjhlkuzHuk-35V0 dummy
scoreboard objectives add h7Z+24T3KY3tZh9E dummy
scoreboard objectives add u3Jl0xeQ_k4hs_EJ dummy
scoreboard objectives add diPB.-EXj+wz5dWU dummy
scoreboard objectives add V5+JAi3.bDXn+.Fe dummy
scoreboard objectives add 1dizpBb7xZBYshzh dummy
scoreboard objectives add l8SPqN-Z7WTziHa4 dummy
scoreboard objectives add 63OvHhfKJIYf0oz. dummy
scoreboard objectives add 7pKY+TG4NAjVlrLN dummy
scoreboard objectives add 7mRu4xtAdpPk__6o dummy
scoreboard objectives add zh3ZtxhYua3jcet8 dummy
scoreboard objectives add t.EUuTA-6uQQ7dmH dummy
scoreboard objectives add OWVfQ6tttSVablvb dummy
scoreboard objectives add o6ndDE_PY.nE1hFX trigger
scoreboard objectives add q+VgAUw43cwwI8Un dummy
scoreboard objectives add +Zkws54XHmUHLT.b dummy
scoreboard objectives add njaGWcBlxIaauhy1 dummy
scoreboard objectives add ulhKLmaWNjfljs.f dummy
scoreboard objectives add d+BOpDqYXVdvuvwe dummy
scoreboard objectives add 696Hax0sTCq2-M4_ dummy
scoreboard objectives add h15Ixi+j-lnqdYCS dummy
scoreboard objectives add w-P7z1-M-LtDzmNv dummy
scoreboard objectives add smlUmtVAobfTw_yd dummy
scoreboard objectives add qPcEev8BKoq_S_q4 dummy
scoreboard objectives add 9cF2Ww7d7IXz1_8m dummy
scoreboard objectives add brSDDwXwSJhNl.yk dummy
scoreboard objectives add Q.njaq3JeI6mSlfy dummy
scoreboard objectives add Tx+mTqUir7wyvJYr dummy
scoreboard objectives add H7-X03DB98HB_pX9 dummy
scoreboard objectives add 1CFbsi89SFX8Wg9o dummy
scoreboard objectives add nStNo-4ZwaYCxLZB dummy
scoreboard objectives add Xw3Y50Cj4YPyg6Mp dummy
scoreboard objectives add 6MR4rYO.usSjLQqr dummy
scoreboard objectives add NMfb1kP78oFgTa+T dummy
scoreboard objectives add +U8qNORHH-lIHubu dummy
scoreboard objectives add VONtJrpA4ZDw9DB1 dummy
scoreboard objectives add 4flGjR+11TUvtLYt trigger
scoreboard objectives add TRX_dNlyiATrVNux dummy
scoreboard objectives add Hu3x9aYJ4DYTDf_c dummy
scoreboard objectives add -_FtvW62yb9wJ8b6 dummy
scoreboard objectives add Jx1d-T3eMKXzm++r dummy
scoreboard objectives add OhM.7BYqSspFoU+h dummy
scoreboard objectives add 2O+lSXhTclSBsPRe dummy
scoreboard objectives add _.9vdh1hU3c.7wz1 dummy
scoreboard objectives add x9.1.q5Bht3HVJvA dummy
scoreboard objectives add lP8tGEZAgzyD-TI- dummy
scoreboard objectives add kDm5vUlMQfm6I4YG dummy
scoreboard objectives add 5dnu+dK3goZrcPTN dummy
scoreboard objectives add XUlX_VvgZLSEJpQ2 dummy
scoreboard objectives add J8wyvgwOgFKDhHLq trigger
scoreboard objectives add fL71fulxkF-LwJH5 dummy
scoreboard objectives add y4wrfjRFj+aPSUnj trigger
scoreboard objectives add 6J0a26xSfJbZH1hh dummy
scoreboard objectives add 6OOW1qdDw7ube-0I dummy
scoreboard objectives add 2TLCnfCJpKny9kbs dummy
scoreboard objectives add 4VdfBDh3+Qvz2B_q dummy
scoreboard objectives add ZRs5EbEap9yjSBc1 dummy
scoreboard objectives add ugKEj3VijBzC7nsL dummy
scoreboard objectives add 2Ts6MMTNxFNCXfXt dummy
scoreboard objectives add lCZI7toi0OahllHV dummy
scoreboard objectives add fY.7CWWx2OSK2pV6 dummy
scoreboard objectives add E8dNha6G28xzdbnC dummy
scoreboard objectives add 5fX4unf-3nVmFPwm dummy
scoreboard objectives add dz+HsFjUglry-S9X dummy
scoreboard objectives add 7DsNK+sVGG60-X1i dummy
scoreboard objectives add dpi3IUWuuk-1wD4c dummy
scoreboard objectives add DRieSsE7TTOKM7hR dummy
scoreboard objectives add cdqYzGEGr0RYjs7F dummy
scoreboard objectives add 0SJr.Wa6NQrtvOLw dummy
scoreboard objectives add oljGfgaAIjwS9ord dummy
scoreboard objectives add mKrbZsAo.jL6nYdB dummy
scoreboard objectives add -mCnkaYbVUZIvV9M dummy
scoreboard objectives add _9TwRiA7sXc2x0HD dummy
scoreboard objectives add -GFWScW-hzxX7n8O dummy
scoreboard objectives add xRvmzd+J.MU+CIQx dummy
scoreboard objectives add cZ3X8oV_T_q+jJ73 dummy
scoreboard objectives add tfGl3wQr8cwFd36+ dummy
scoreboard objectives add WmWpGWk4ytU6Tpp3 dummy
scoreboard objectives add rL7g64MDn0hexjAB dummy
scoreboard objectives add k5zfYp8tAQQvHd9A dummy
scoreboard objectives add QUQSde960mt3GKo1 minecraft.custom:minecraft.sprint_one_cm
scoreboard objectives add dcExTKWiSmEN.A2U dummy
scoreboard objectives add 7ttCqqDdGtcucU.d dummy
scoreboard objectives add r1eJXB6TPSYqP80i dummy
scoreboard objectives add tgAgfbR9X+tpAt2l dummy
scoreboard objectives add MUgn5xlFLUP78+qi dummy
scoreboard objectives add jLjsIRdqa_vqspAk dummy
scoreboard objectives add xGmki3.eMTVpN8Qv dummy
scoreboard objectives add gP5I-SHVLLMk8UpQ dummy
scoreboard objectives add RzwIXk15WUYOQ3Uc minecraft.custom:minecraft.damage_taken
scoreboard objectives add 35OcA9ItS421vswb dummy
scoreboard objectives add eNF-_jkvef2iWyoe dummy
scoreboard objectives add 2SjdhdwoKAoZNCGD dummy
scoreboard objectives add TJiQ-IXLkzwmG+Kc dummy
scoreboard objectives add V0AlsLB.TP5Yn0LW totalKillCount
scoreboard objectives add 4SOWLfg+1Vi9McFf dummy
scoreboard objectives add 18zMeDkPNbIl-1xm dummy
scoreboard objectives add Auhld_P2aFfAldnr minecraft.custom:minecraft.damage_taken
scoreboard objectives add DFEwbH8lwoZnDv5U dummy
scoreboard objectives add uVxvqa1heInT9476 dummy
scoreboard objectives add 7ZQCN5ejQnhyi5k3 minecraft.custom:minecraft.damage_taken
scoreboard objectives add 8WG6l7xUM2qLETLh dummy
scoreboard objectives add hpe70m3fPrVuw4cS dummy
scoreboard objectives add j_CRJH+7y0jd8dKM minecraft.custom:minecraft.damage_taken
scoreboard objectives add jx-QDTut0ImlbCj2 dummy
scoreboard objectives add jHjfAYjMIhJdPZ2U dummy
scoreboard objectives add SAdqAytfQGZK-0lR dummy
scoreboard objectives add E2N.Q0DA7a81k6z1 dummy
scoreboard objectives add 2MCrw5Zo.Hr4zO0j dummy
scoreboard objectives add _MKV1TR8+6GaXkyP dummy
scoreboard objectives add iTTM_42CBwAkpmm4 dummy
scoreboard objectives add XRFkpb.IBxC-c.jz dummy
scoreboard objectives add nxvsoUOlRoc+8QzP dummy
scoreboard objectives add bFFb+KSbu3lU-6p2 dummy
scoreboard objectives add TiX_arBEjB3wjyO- dummy
scoreboard objectives add GV8tuMOdbZ4UA-ZH dummy
scoreboard objectives add DqG9ild4msBc7lxA dummy
scoreboard objectives add ofuKFQanDPSo9zPh dummy
scoreboard objectives add Upxdgs7NkEDHy2Z2 dummy
scoreboard objectives add 1JxLHHF6KF0qT.x7 dummy
scoreboard objectives add ZqOuobjQA5a47p9M dummy
scoreboard objectives add a_Hlg46EEKZ5HeqU dummy
scoreboard objectives add VAvMKyH6PyBqQDE1 totalKillCount
scoreboard objectives add pLWp4cNKIi04fqv5 totalKillCount
scoreboard objectives add z-N-Wt7a9nKDNlmK totalKillCount
scoreboard objectives add E2psAUk.-htOhUrf dummy
scoreboard objectives add or3c_L6Glp0dB4Tc minecraft.custom:minecraft.damage_dealt
scoreboard objectives add Kbg64j-eBraq0MZ8 dummy
scoreboard objectives add aWxeXD6_nm4RnnWG dummy
scoreboard objectives add l6+HLI_8Igx7aG.V dummy
scoreboard objectives add tuOydgnmaaQ6LHx_ dummy
scoreboard objectives add EjZrTTSQvqefWp-e dummy
scoreboard objectives add d1kDePtoGaW6oZQ_ minecraft.used:minecraft.chorus_fruit
scoreboard objectives add ejYPGG9j6ejZYsl1 trigger
scoreboard objectives add aibgtz8jimpcdGKj trigger
scoreboard objectives add pHOQ+nVeACV4acS- dummy
scoreboard objectives add 5NYuI1MRqVcOWssO dummy
scoreboard objectives add A89mYp_e2BN0XjT_ dummy
scoreboard objectives add uhSv3BylkH1.SVb4 dummy
scoreboard objectives add K0E-Eg6I4gJ8ZIuS dummy
scoreboard objectives add ZYfjBnR5YFekZV+A dummy
scoreboard objectives add d2Ca.dirkAgGp6Qw dummy
scoreboard objectives add .MIdEKFSIgEFqj42 dummy
scoreboard objectives add 2-wbZdQCr-hyVYHi dummy
scoreboard objectives add dJXuXJ0RpqBsoj-W dummy
scoreboard objectives add KzB4C48AY7vAzGBT dummy
scoreboard objectives add kxjlR81y8FVlY0BM dummy
scoreboard objectives add 1RBxq8Yd4q8ec_Hs dummy
scoreboard objectives add Nig34s2VJZKP+A2Q dummy
scoreboard objectives add JsTcLyAg5VaSitc_ dummy
scoreboard objectives add huwi+YuwDB.Nvers trigger
scoreboard objectives add f.EAu0RkdNmJ_9lm dummy
scoreboard objectives add VbCeuk3zxkoi1si2 dummy
scoreboard objectives add hQB2o2UQI9C.W6rB dummy
scoreboard objectives add PaicO9s7uZoV0A3h dummy
scoreboard objectives add Ws_rA1hA09l7asI9 dummy
scoreboard objectives add -XCMcJv__pS2ybgn trigger
scoreboard objectives add NjBa8xXTNSecj9P2 dummy
scoreboard objectives add KgrsXRT9OLFIblvO dummy
scoreboard objectives add HJk_GSxgEzKYRk21 dummy
scoreboard objectives add X2BsKPR+9voe__Iw dummy
scoreboard objectives add zTwr.H95ceejbn11 dummy
scoreboard objectives add KrpwflfviGntPBkH dummy
scoreboard objectives add yK2Hhc7yM4+pcrb5 trigger
scoreboard objectives add rB6vUOF5HGj8bZRa dummy
scoreboard objectives add SwnMGeA9U4ih5hiq trigger
scoreboard objectives add lQb_PdyMTVMKCV3+ dummy
scoreboard objectives add PyfSRUxlgQpvtIXN dummy
scoreboard objectives add hy3u_OGAlpwlZn5d dummy
scoreboard objectives add Y9Y5-McscoS2X2Tw dummy
scoreboard objectives add ke.nXkSNswbs3xI_ dummy
scoreboard objectives add k4OzSIx-_awyPAr0 dummy
scoreboard objectives add wmr1jSVoD3yTFRjr dummy
scoreboard objectives add t-tKVXNbB5WT5hf+ dummy
scoreboard objectives add iTRw-aj2OMBf_jNZ trigger
scoreboard objectives add jlTfWFVPywg5_DLH dummy
scoreboard objectives add ia-otN-0ZQk4D86J dummy
scoreboard objectives add PJca2fPQlIGfiThu dummy
scoreboard objectives add D_964L4Udf0MzIey trigger
scoreboard objectives add lYtYWHRw7I1-GS.J dummy
scoreboard objectives add 0AEJXSUAuG6rKLXb dummy
scoreboard objectives add ZKC_2WF+tH3xFryq dummy
scoreboard objectives add _2Yw.eu7xIJr00Ub trigger
scoreboard objectives add inpuWcnutBsaGM3Z dummy
scoreboard objectives add ZaI9Kjwvb-i9PsME dummy
scoreboard objectives add ERn-NAAm9NnMoKgR dummy
scoreboard objectives add T.d.s02MX+2y8qqP trigger
scoreboard objectives add g65hK21X6TRGdjr0 dummy
scoreboard objectives add oHeFVx6Fk00QQmpo dummy
scoreboard objectives add g.K-oAjQnR4u8FzB dummy
scoreboard objectives add +JGstOX82AT3vOTh trigger
scoreboard objectives add jX+4Xjb.MWLDuue. dummy
scoreboard objectives add slu2exMd5HTEZqLH dummy
scoreboard objectives add vMx96cnN3AHJyqh. dummy
scoreboard objectives add yt8HsJDnc7Ai12b0 trigger
scoreboard objectives add B5oL55hVEPX0jk6a dummy
scoreboard objectives add NCH5fb3V3xxesejZ dummy
scoreboard objectives add _fR86MwXkIq63tgO dummy
scoreboard objectives add CM.dXDRp7_9HtMe6 dummy
scoreboard objectives add Oj7Fr_ZGWiza3VcK trigger
scoreboard objectives add PSK265zyV0tcakg. dummy
scoreboard objectives add e2U3SpDQbc2ipeRu dummy
scoreboard objectives add t+zTRnuPewoX6aZG dummy
scoreboard objectives add BMgI9mzNKaZ6nEOi dummy
scoreboard objectives add tr3irtSGHNgEMVKE dummy
scoreboard objectives add N7rG1mUTou0Eanzy dummy
scoreboard objectives add _coW.GEz8k8KGpIi dummy
scoreboard objectives add 2Q-3CBwvcI2xU_fa dummy
scoreboard objectives add TLcY72FHECTf.vZU dummy
scoreboard objectives add EY5IXyXQon6LNWOr dummy
scoreboard objectives add 0YjP_F.RG4sMI9W1 dummy
scoreboard objectives add GvZ6o4Fjf3G+nb5N trigger
scoreboard objectives add mf9L5CC4VvVuq_LG dummy
scoreboard objectives add 4SPCRPhK90WQgUSy dummy
scoreboard objectives add c3L7p0EKEodSwBGT trigger
scoreboard objectives add 16Ubn76t+IUTS2SG dummy
scoreboard objectives add rAn8jHRy+t_ySM9V dummy
scoreboard objectives add WM9zJpevK_lz6Fc3 trigger
scoreboard objectives add 3snzXODVU_dFbZbk dummy
scoreboard objectives add Huym6oDV.36mHpgO dummy
scoreboard objectives add -GItc0MID8K66M+X trigger
scoreboard objectives add gW-d+dbp7HABHHo_ dummy
scoreboard objectives add XXjZkC1d.-N2Lw1N dummy
scoreboard objectives add s056Bt8HQQ0EEGTQ dummy
scoreboard objectives add Z5ljSJsbV5V1TuIt trigger
scoreboard objectives add 51-F_zRtwqnlordZ dummy
scoreboard objectives add eMpETRIEVKrVQ.gG dummy
scoreboard objectives add FDr4vVXF.e_l+gMp trigger
scoreboard objectives add DMvJy39j12DX9Kb9 dummy
scoreboard objectives add w2vXG8MhDMaATip- dummy
scoreboard objectives add PDM93RyClnanxL2G dummy
scoreboard objectives add gQW1rxxfIXPfzaDd trigger
scoreboard objectives add bxQyofYZeil+1tnp dummy
scoreboard objectives add -jbbmzZkgkWlndcw dummy
scoreboard objectives add uhzKfkXAIefMayKd dummy
scoreboard objectives add hDGAU3BI-Xo_oIq4 trigger
scoreboard objectives add DO9-_zcf6dtt7.qH dummy
scoreboard objectives add vXkCguF8haDEQwzE dummy
scoreboard objectives add yRtar7pbWHdPQtZX dummy
scoreboard objectives add 3eeNDiceQNWpQC.R dummy
scoreboard objectives add tjldNRFoNkOmgfkt dummy
scoreboard objectives add oI7Ur1+Oz4lXBySN dummy
scoreboard objectives add 2YDePdG0g9rahp.l trigger
scoreboard objectives add +Nl1uwuz0GnH7Kmf dummy
scoreboard objectives add sVVe8K-SP6YS.MBG dummy
scoreboard objectives add yvbQw36HM1W.ldmU trigger
scoreboard objectives add Sbfrt5MsOhaDvfxj dummy
scoreboard objectives add DN4S60dfb7jnRc3p dummy
scoreboard objectives add dXl0aV9coU1bEgjb dummy
scoreboard objectives add qzyYqzn1MCUmUSiq dummy
scoreboard objectives add NjB73iJ.dHxzzN45 trigger
scoreboard objectives add wgJcl0i0dQEo9-wl dummy
scoreboard objectives add GgR4ufr+n70nbQQT trigger
scoreboard objectives add SiHCdKv8jijibnll dummy
scoreboard objectives add .J2dwrC_k+.pju-N dummy
scoreboard objectives add HH_hIa5wR.7hEKJ2 dummy
scoreboard objectives add O3J.DEEVwelT5GRd dummy
scoreboard objectives add 9GNSmfON.qpRKIcv trigger
scoreboard objectives add fHnAAtZJka5g8J_h dummy
scoreboard objectives add Mw3V.LQ7BZ24pM6o dummy
scoreboard objectives add A6GuOZTXg6XmcY9C trigger
scoreboard objectives add wqKEjHMOmBCYMYWw dummy
scoreboard objectives add MjFcSNTJ+tIZmwuU dummy
scoreboard objectives add OtwO.0gl3AzzqcGg trigger
scoreboard objectives add iLssNGWZGo1tm_SW dummy
scoreboard objectives add v9jW.czrPQqAmyJO dummy
scoreboard objectives add meQKQ6KU0BsgzT-n dummy
scoreboard objectives add Cs2_o6CnejbMXuGg dummy
scoreboard objectives add IDCivBfR7SA0Ag.s dummy
scoreboard objectives add t44CDG+k-gJJDETL trigger
scoreboard objectives add ULZ0kSpgK.izJyW0 dummy
scoreboard objectives add UYNzm3LAW-fGr9SC dummy
scoreboard objectives add B+3OdTGv96SdMc8O dummy
scoreboard objectives add Tl8TCZteT5Hpi3Zi trigger
scoreboard objectives add rJlOYVUlCP.pfkfL dummy
scoreboard objectives add S3bv3mSmrtX6ujx. dummy
scoreboard objectives add ._N4fEA1e35858cG dummy
scoreboard objectives add GTvTuFK0LFgY_Nq_ trigger
scoreboard objectives add .+r7ZWqFDOL7k0g3 dummy
scoreboard objectives add s6tN1tVPF0dU_no5 dummy
scoreboard objectives add nZASHLMQmmzgyOf- dummy
scoreboard objectives add a543XRvs-DnCeX-g trigger
scoreboard objectives add Atls8bdBB8WyFTK6 dummy
scoreboard objectives add UMuUxgZEwM8bXzpD dummy
scoreboard objectives add OkuJS80HP1.FS6U0 dummy
scoreboard objectives add 6+sK5ENugUjbDE0u trigger
scoreboard objectives add GqGCOAQCKZzWWtnA dummy
scoreboard objectives add qbY8JUzytKV1fMAf dummy
scoreboard objectives add 6.2AorKv+BvhodYc trigger
scoreboard objectives add zJYp0n7A5gWPwH30 dummy
scoreboard objectives add .P+7uOryj-EeVYXn dummy
scoreboard objectives add HwpQcdLpbuILYtv6 dummy
scoreboard objectives add YzFiVxl87EThuH74 dummy
scoreboard objectives add _RHfAZAPS4NgzhOe dummy
scoreboard objectives add 89oEFBhff7NTPJfr dummy
scoreboard objectives add PU22TEpia-f4eDq0 dummy
scoreboard objectives add Ha5thUbt.9ekqaSU dummy
scoreboard objectives add yh2wvtOv+T7KnhMy dummy
scoreboard objectives add G9P_+8ET7SBTdXQA dummy
scoreboard objectives add +03L9sSw-46Hj7GE dummy
scoreboard objectives add ycVIZpdBde07TgY_ dummy
scoreboard objectives add Wynew5+9XEiexuNQ dummy
scoreboard objectives add G-9FYrnBa_jbx5cO deathCount
scoreboard objectives add Yo4l+UC28wCYzo3N dummy
scoreboard objectives add CdjNRalhmu9tPgeZ dummy
scoreboard objectives add OqTgWWbzTAJhEFWB dummy
scoreboard objectives add t4E0nDh9d-mf-NWm dummy
scoreboard objectives add jsmfo6BApdA+Odxz armor
scoreboard objectives add p0K7ube92zt1KLdd dummy
scoreboard objectives add gUvfoPhMcDL43EFW dummy
scoreboard objectives add .n+Ku4x4SlSH71q6 minecraft.custom:minecraft.jump
scoreboard objectives add TS.HSzFsEwztzCWy dummy
scoreboard objectives add UT_CFyBdDLld32mf dummy
scoreboard objectives add 3A6DV6aBtlrvfUdY dummy
scoreboard objectives add t-HuWjsg3ecNGN3H dummy
scoreboard objectives add 2qK4Fl_WgJOh1TIi dummy
scoreboard objectives add u8_LM8pVN+4ZuJTg dummy
scoreboard objectives add lKQokmIKrzeTsb8X dummy
scoreboard objectives add -IVrnYMncYudVBKb dummy
scoreboard objectives add f6EsVaz1LRBBgKlL dummy
scoreboard objectives add XgQMvSImyi__5Xn8 minecraft.custom:minecraft.sprint_one_cm
scoreboard objectives add 83WB9D6gWIstJQEX dummy
scoreboard objectives add a9+3AaYB2T3Emndm dummy
scoreboard objectives add Wflg08g2-2-hFqE2 dummy
scoreboard objectives add CCfT7iia4CiZa5lp dummy
scoreboard objectives add meWd3gh1Fw9eRNHa minecraft.custom:minecraft.sneak_time
scoreboard objectives add M5XY0lxFiHCmMpIW dummy
scoreboard objectives add ZDlaB-2ikDOlGoIK dummy
scoreboard objectives add bbeVDWnYH7OPFfhY dummy
scoreboard objectives add ExyecUH1tlEPF9AF dummy
scoreboard objectives add tuQ38nWRJBDHfAqp dummy
scoreboard objectives add 3CIIyvahA5ZencZL dummy
scoreboard objectives add 1E8h838iHlE9GVRi totalKillCount
scoreboard objectives add 0bdigT8QZh-Tb5Ky dummy
scoreboard objectives add -AOGCkxsXDa-Lugn minecraft.used:minecraft.iron_axe
scoreboard objectives add 4f7kxl_caN4KxF7m minecraft.used:minecraft.golden_sword
scoreboard objectives add 3X6+i_nvGwa5aoV0 minecraft.used:minecraft.iron_hoe
scoreboard objectives add dEBCQUV9IWZZO1HF minecraft.used:minecraft.iron_shovel
scoreboard objectives add OKBH2MK0hMmBIotZ dummy
scoreboard objectives add k.gUKqads4Z0IALN minecraft.used:minecraft.diamond_hoe
scoreboard objectives add 4EXq.wK0x6lvYLNn dummy
scoreboard objectives add khNWBTqwuWpUIiga dummy
scoreboard objectives add zXT81+i248eTnAdr minecraft.used:minecraft.diamond_axe
scoreboard objectives add 1QtXQ982FK_XOGN4 minecraft.used:minecraft.diamond_sword
scoreboard objectives add lfk4TIjj2yeNddBD dummy
scoreboard objectives add vcNStpVGti05PCsw dummy
scoreboard objectives add ZzsdDzIMf5kOoFj0 minecraft.used:minecraft.iron_sword
scoreboard objectives add NdDP38w88s0KS9Jx dummy
scoreboard objectives add ty6DDx8GQnwHpl5c minecraft.used:minecraft.stone_sword
scoreboard objectives add tbJElevLWHw0_ZBf minecraft.used:minecraft.diamond_pickaxe
scoreboard objectives add aSh+7PPN8epQpor1 minecraft.used:minecraft.stone_pickaxe
scoreboard objectives add 8JsJUk0oxfhE7Bfx minecraft.used:minecraft.wooden_axe
scoreboard objectives add N+E2TE2nGpkcLWvJ dummy
scoreboard objectives add TraYMyy2j+wXdWTd dummy
scoreboard objectives add gJTDbTuS_31TngsJ minecraft.used:minecraft.stone_axe
scoreboard objectives add .MBp1foOO_Jyv1t0 minecraft.used:minecraft.diamond_shovel
scoreboard objectives add ciUiEA0lCW8ZyIdU minecraft.used:minecraft.wooden_sword
scoreboard objectives add XiQqusWThXNU_DMy dummy
scoreboard objectives add .X8bsceFXGZ1EYfU minecraft.used:minecraft.wooden_pickaxe
scoreboard objectives add OZvGIvAqvuYtG9.q dummy
scoreboard objectives add 3Xx.H9a4TCtn2Nx5 dummy
scoreboard objectives add GizMGXf0PpUCUQ12 dummy
scoreboard objectives add Ut3T6sVtvwky-s9. dummy
scoreboard objectives add zlzTdHb-2BiBPjQS dummy
scoreboard objectives add 7aOSN03P6JOuJb2T dummy
scoreboard objectives add NkSeJLVTgh15aSIf dummy
scoreboard objectives add l5r+Zt_hrBNOQTGS dummy
scoreboard objectives add PrR_UJXrYJj-PG3b dummy
scoreboard objectives add VA40egdlWgmfSP0I dummy
scoreboard objectives add GsNCaun8SPm47f6I minecraft.used:minecraft.bow
scoreboard objectives add fa75zKRTCKc9sgbm dummy
scoreboard objectives add lKwXj_EPcwT8FhXX dummy
scoreboard objectives add -mEVYqvfZfY0_uJW dummy
scoreboard objectives add ZkXK0-CnHDQanCec dummy
scoreboard objectives add t1MrZNiKl5cb5y4H dummy
scoreboard objectives add HJ9.yufAsB58B0j2 dummy
scoreboard objectives add w68o1Pz3X_lMnXN0 dummy
scoreboard objectives add 64305VjbPCxtu5c+ dummy
scoreboard objectives add 7_nmW6_RDc2wZGSa deathCount
scoreboard objectives add RgRS0RCdvPopotAr totalKillCount
scoreboard objectives add rqAdY5cn5wLbxeB- dummy
scoreboard objectives add JrW6nhgP1OBW5OmK dummy
scoreboard objectives add gaQvNe-MmGWybY07 dummy
scoreboard objectives add .pnfhTsq36mptu.. dummy