summon minecraft:arrow ~-1.36 ~1.47 ~ {<#KurnasSouthArrowTags#>}
summon minecraft:arrow ~-0.47 ~0.48 ~ {<#KurnasSouthSilentArrowTags#>}
summon minecraft:arrow ~-1.0 ~2.33 ~ {<#KurnasSouthSilentArrowTags#>}
summon minecraft:arrow ~0.84 ~0.63 ~ {<#KurnasSouthSilentArrowTags#>}
summon minecraft:arrow ~-0.57 ~1.63 ~ {<#KurnasSouthSilentArrowTags#>}
summon minecraft:arrow ~0.06 ~1.07 ~ {<#KurnasSouthSilentArrowTags#>}
summon minecraft:arrow ~-1.36 ~0.6 ~ {<#KurnasSouthSilentArrowTags#>}
summon minecraft:arrow ~-0.21 ~2.57 ~ {<#KurnasSouthSilentArrowTags#>}
summon minecraft:arrow ~-0.89 ~3.78 ~ {<#KurnasSouthSilentArrowTags#>}
summon minecraft:arrow ~0.98 ~2.2 ~ {<#KurnasSouthSilentArrowTags#>}
summon minecraft:arrow ~-0.11 ~3.46 ~ {<#KurnasSouthSilentArrowTags#>}
summon minecraft:arrow ~0.79 ~3.33 ~ {<#KurnasSouthSilentArrowTags#>}
summon minecraft:arrow ~1.35 ~1.45 ~ {<#KurnasSouthSilentArrowTags#>}