function tlkot:<~>/burrows_trap
function tlkot:<~>/cavern_hall_floor_trap
function tlkot:<~>/fall_from_sky
function tlkot:<~>/prepared_crystal
function tlkot:<~>/tutorial_teleport
function tlkot:<~>/warden_smoke
function tlkot:<~>/warding_torch

function tlkot:<~>/arrow_trap/main
function tlkot:<~>/burner/main
function tlkot:<~>/bridge_collapse/main
function tlkot:<~>/blood_sigil_tutorial/main
function tlkot:<~>/casting_lab_01_blackout/main
function tlkot:<~>/cavern_water_trap/main
function tlkot:<~>/cavern_rising_water_room/main
function tlkot:<~>/cursed_pools/main
function tlkot:<~>/drowning_cage/main
function tlkot:<~>/gate/main
function tlkot:<~>/government_tunnels_tripwires/main
function tlkot:<~>/imprint_resonance_sigil/main
function tlkot:<~>/ixinik_fall/main
function tlkot:<~>/kill_zones/main
function tlkot:<~>/pit_traps/main
function tlkot:<~>/puppet_chase/main
function tlkot:<~>/psychiatric_ward_tripwires/main
function tlkot:<~>/recall_memory/main
function tlkot:<~>/saviour_moses_teleport/main
function tlkot:<~>/seals/main
function tlkot:<~>/transfixed_caster/main
function tlkot:<~>/vaults_of_time/main