summon minecraft:arrow ~1.03 ~3.09 ~ {<#KurnasNorthArrowTags#>}
summon minecraft:arrow ~0.06 ~3.56 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~1.21 ~2.13 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~-0.74 ~3.17 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~0.09 ~2.57 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~0.29 ~1.68 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~-0.62 ~2.13 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~-1.35 ~2.46 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~-1.12 ~1.49 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~-1.4 ~0.3 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~-0.42 ~0.54 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~0.77 ~0.37 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~1.38 ~1.27 ~ {<#KurnasNorthSilentArrowTags#>}