summon minecraft:arrow ~-0.32 ~1.09 ~ {<#KurnasNorthArrowTags#>}
summon minecraft:arrow ~0.58 ~2.13 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~0.72 ~0.48 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~1.08 ~1.32 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~-0.37 ~0.13 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~-1.25 ~0.12 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~-0.21 ~1.99 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~-1.27 ~1.35 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~0.61 ~3.13 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~1.38 ~2.7 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~-1.09 ~2.14 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~-0.67 ~3.14 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~1.34 ~3.51 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~-0.02 ~3.66 ~ {<#KurnasNorthSilentArrowTags#>}