summon minecraft:arrow ~-1.33 ~1.78 ~ {<#KurnasNorthArrowTags#>}
summon minecraft:arrow ~-0.42 ~0.81 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~-0.72 ~2.96 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~-0.01 ~2.08 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~0.4 ~1.32 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~1.03 ~0.2 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~-0.02 ~3.48 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~1.07 ~3.21 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~-1.2 ~3.64 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~0.12 ~0.12 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~1.16 ~1.62 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~-1.02 ~0.26 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~1.31 ~2.45 ~ {<#KurnasNorthSilentArrowTags#>}