summon minecraft:arrow ~-0.21 ~2.84 ~ {<#KurnasNorthArrowTags#>}
summon minecraft:arrow ~0.82 ~3.66 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~0.8 ~2.03 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~1.35 ~2.88 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~-0.34 ~3.74 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~-0.31 ~1.42 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~0.7 ~0.8 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~-1.07 ~3.23 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~-0.91 ~0.82 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~-0.23 ~0.29 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~1.38 ~1.39 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~-0.68 ~2.17 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~-1.34 ~0.05 ~ {<#KurnasNorthSilentArrowTags#>}