summon minecraft:arrow ~-0.97 ~1.73 ~ {<#KurnasNorthArrowTags#>}
summon minecraft:arrow ~-0.72 ~2.55 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~-0.55 ~0.58 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~-1.39 ~0.48 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~0.01 ~1.19 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~0.12 ~2.08 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~-0.08 ~3.44 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~0.9 ~2.56 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~0.86 ~1.14 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~0.92 ~0.3 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~1.28 ~1.84 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~-1.1 ~3.42 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~0.9 ~3.78 ~ {<#KurnasNorthSilentArrowTags#>}
summon minecraft:arrow ~0.17 ~ ~ {<#KurnasNorthSilentArrowTags#>}