tag @e remove LastSummoned

execute if entity @s[tag=Enemy.Dirty-Boots] run function tlkot:<~>/enemy/dirty/boots
execute if entity @s[tag=Enemy.Dirty-Chest] run function tlkot:<~>/enemy/dirty/chest
execute if entity @s[tag=Enemy.Dirty-Helmet] run function tlkot:<~>/enemy/dirty/helmet
execute if entity @s[tag=Enemy.Dirty-Shovel] run function tlkot:<~>/enemy/dirty/shovel
execute if entity @s[tag=CrystalGuardianHitbox] run function tlkot:<~>/enemy/crystal_guardian_hitbox
execute if entity @s[tag=Enemy.Possession] run function tlkot:<~>/enemy/possession
execute if entity @s[tag=Enemy.Hunter-All] run function tlkot:<~>/enemy/hunter/all
execute if entity @s[tag=Enemy.Hunter-NoHelmet] run function tlkot:<~>/enemy/hunter/no_helmet
execute if entity @s[tag=Enemy.Hunter-NoChest] run function tlkot:<~>/enemy/hunter/no_chest
execute if entity @s[tag=Enemy.Hunter-ChainHelmet] run function tlkot:<~>/enemy/hunter/chain_helmet
execute if entity @s[tag=Enemy.Hunter-FireNoHelmet] run function tlkot:<~>/enemy/hunter/fire/no_helmet
execute if entity @s[tag=Enemy.Hunter-FireNoChest] run function tlkot:<~>/enemy/hunter/fire/no_chest
execute if entity @s[tag=Enemy.Hunter-FireChainHelmet] run function tlkot:<~>/enemy/hunter/fire/chain_helmet
execute if entity @s[tag=Enemy.Noble-Hoe] run function tlkot:<~>/enemy/noble/hoe
execute if entity @s[tag=Enemy.Noble-NoHand] run function tlkot:<~>/enemy/noble/no_hand
execute if entity @s[tag=Enemy.Noble-Angry] run function tlkot:<~>/enemy/noble/angry
execute if entity @s[tag=Enemy.Knight-Medium] run function tlkot:<~>/enemy/knight/medium
execute if entity @s[tag=Enemy.Knight-Melee] run function tlkot:<~>/enemy/knight/melee
execute if entity @s[tag=Enemy.Knight-Ranged] run function tlkot:<~>/enemy/knight/ranged
execute if entity @s[tag=Enemy.Knight-Starving] run function tlkot:<~>/enemy/knight/starving
execute if entity @s[tag=Enemy.SmokeBeast] run function tlkot:<~>/enemy/smoke_beast/normal
execute if entity @s[tag=Enemy.ProximitySmokeBeast] run function tlkot:<~>/enemy/smoke_beast/proximity
execute if entity @s[tag=Enemy.Spider-Flaming] run function tlkot:<~>/enemy/spider/flaming
execute if entity @s[tag=Enemy.Spider-Cave] run function tlkot:<~>/enemy/spider/cave
execute if entity @s[tag=Enemy.Spider-Normal] run function tlkot:<~>/enemy/spider/normal
execute if entity @s[tag=Enemy.CasterReaper-Wither] run function tlkot:<~>/enemy/caster/reaper/wither
execute if entity @s[tag=Enemy.CasterReaper-Levitating] run function tlkot:<~>/enemy/caster/reaper/levitating
execute if entity @s[tag=Enemy.CasterReaper-Healing] run function tlkot:<~>/enemy/caster/reaper/healing
execute if entity @s[tag=Enemy.CasterReaper-Dread] run function tlkot:<~>/enemy/caster/reaper/dread
execute if entity @s[tag=Enemy.CasterReaper-Transform] run function tlkot:<~>/enemy/caster/reaper/transform
execute if entity @s[tag=Enemy.UndeadCaster-General] run function tlkot:<~>/enemy/caster/undead/general
execute if entity @s[tag=Enemy.UndeadCaster-Dread] run function tlkot:<~>/enemy/caster/undead/dread
execute if entity @s[tag=Enemy.SubjugateCaster] run function tlkot:<~>/enemy/caster/subjugate
execute if entity @s[tag=Enemy.Dread] run function tlkot:<~>/enemy/dread
execute if entity @s[tag=Enemy.DreadExile] run function tlkot:<~>/enemy/dread_exile/normal
execute if entity @s[tag=Enemy.NoDreadExile] run function tlkot:<~>/enemy/dread_exile/none
execute if entity @s[tag=Enemy.DreadReaper] run function tlkot:<~>/enemy/dread_reaper/normal
execute if entity @s[tag=Enemy.NoDreadReaper] run function tlkot:<~>/enemy/dread_reaper/none
execute if entity @s[tag=Enemy.Wolf-Normal] run function tlkot:<~>/enemy/wolf/normal
execute if entity @s[tag=Enemy.Wolf-Dread] run function tlkot:<~>/enemy/wolf/dread
execute if entity @s[tag=Enemy.Wolf-DreadTrap] run function tlkot:<~>/enemy/wolf/dread_trap
execute if entity @s[tag=Enemy.Undead-Fisher,tag=!AI.Faithful] run function tlkot:<~>/enemy/undead/fisher
execute if entity @s[tag=Enemy.Undead-Normal,tag=!AI.Faithful] run function tlkot:<~>/enemy/undead/normal
execute if entity @s[tag=Enemy.Undead-Digger,tag=!AI.Faithful] run function tlkot:<~>/enemy/undead/digger
execute if entity @s[tag=Enemy.Undead-Farmer,tag=!AI.Faithful] run function tlkot:<~>/enemy/undead/farmer
execute if entity @s[tag=Enemy.Undead-Warrior] run function tlkot:<~>/enemy/undead/warrior
execute if entity @s[tag=Enemy.Undead-Berserker] run function tlkot:<~>/enemy/undead/berserker
execute if entity @s[tag=Enemy.Undead-Seeker] run function tlkot:<~>/enemy/undead/seeker
execute if entity @s[tag=Enemy.Undead-Fisher,tag=AI.Faithful] run function tlkot:<~>/enemy/undead/faithful/fisher
execute if entity @s[tag=Enemy.Undead-Normal,tag=AI.Faithful] run function tlkot:<~>/enemy/undead/faithful/normal
execute if entity @s[tag=Enemy.Undead-Digger,tag=AI.Faithful] run function tlkot:<~>/enemy/undead/faithful/digger
execute if entity @s[tag=Enemy.Undead-Farmer,tag=AI.Faithful] run function tlkot:<~>/enemy/undead/faithful/farmer
execute if entity @s[tag=Enemy.Spore-Poison] run function tlkot:<~>/enemy/spore/poison
execute if entity @s[tag=Enemy.Spore-Slowness] run function tlkot:<~>/enemy/spore/slowness
execute if entity @s[tag=Enemy.LivingMass] run function tlkot:<~>/enemy/living_mass
execute if entity @s[tag=Enemy.Intangible] run function tlkot:<~>/enemy/intangible
execute if entity @s[tag=Enemy.IronGuard] run function tlkot:<~>/enemy/iron_guard
execute if entity @s[tag=Enemy.Thunderstruck] run function tlkot:<~>/enemy/thunderstruck
execute if entity @s[tag=Enemy.StoneGuardian] run function tlkot:<~>/enemy/stone_guardian
execute if entity @s[tag=Enemy.Blighted] run function tlkot:<~>/enemy/blighted
execute if entity @s[tag=Enemy.Starving] run function tlkot:<~>/enemy/starving
execute if entity @s[tag=Enemy.Sentinel] run function tlkot:<~>/enemy/sentinel
execute if entity @s[tag=Enemy.Necromancer] run function tlkot:<~>/enemy/necromancer
execute if entity @s[tag=Enemy.Infested] run function tlkot:<~>/enemy/infested
execute if entity @s[tag=Enemy.Hollow] run function tlkot:<~>/enemy/hollow
execute if entity @s[tag=Enemy.SoulTaster] run function tlkot:<~>/enemy/soul_taster
execute if entity @s[tag=Enemy.PunchingBag-1] run function tlkot:<~>/enemy/punching_bag/1
execute if entity @s[tag=Enemy.PunchingBag-2] run function tlkot:<~>/enemy/punching_bag/2
execute if entity @s[tag=Enemy.LichSpawn] run function tlkot:<~>/enemy/lich_spawn
execute if entity @s[tag=Enemy.ManBull] run function tlkot:<~>/enemy/man_bull

execute if entity @e[tag=LastSummoned] run function tlkot:<~>/store_data/main